---
output:
  word_document
bibliography: references.bib
---


# Designing and implementing a longitudinal rodent trapping study to investigate rodent community structures along a land use gradient in Eastern Sierra Leone {#methodschapter}


## Preface


Unbiased estimates of small-mammal species presence and absence are required to model the association of species occupancy with land use type  [@peterson_ecological_2011; @stolar_accounting_2015]. Available rodent trapping data from the Eastern Province of Sierra Leone was not amenable to these analyses, as rodent sampling has generally been conducted as opportunistic surveillance to measure LASV prevalence or for cataloguing rodent species as part of environmental impact assessments for resource extraction or construction [@fraser_lassa_1974; @monath_lassa_1974; @keenlyside_case-control_1983; @barnett_ecology_2000; @bonner_poor_2007; @decher_small_2010]. Therefore, I designed and implemented a longitudinal rodent trapping study to investigate whether rodent species richness and diversity vary along a land use gradient (results reported in Chapter \@ref(chapter3)) and whether rodent species involved in LASV transmission have increased contact rates to other individuals capable of pathogen maintenance (results reported in Chapter \@ref(chapter4)). 


This methodology chapter draws on current best-practice in small-mammal sampling in West Africa in addition to reporting novel methodological developments. Specifically, this chapter provides 1) information about how local support and knowledge were leveraged to inform the design of the study protocol and 2) technical details on the sampling strategy, data collection tools, biological sample processing, data cleaning and management steps. It is envisioned that documenting and providing evidence for decisions taken in designing this study will aid in the harmonisation and reproducibility of rodent trapping studies across the region.


## Leveraging local support and knowledge


For any rodent trapping study in village communities, it is vital to ensure that local communities support the study. This is particularly important for longitudinal studies with repeat visits. I was aware that study activities could be associated with stigma (i.e., sampling wildlife for viral pathogens); it was therefore important that study villages considered this prior to providing permission for us to begin sampling. To optimise the continuing support received from the local communities, the study protocol was described in detail to the local chieftain and the village committee. All concerns about the risk to the local community from our activities and the impact we may have on their activities were addressed and we committed to employing community members during our sampling activities. An exit interview was scheduled where we shared our findings with the villages (conducted in February 2023). During these interviews, we explored the positive and negative impact of our sampling activities. All villages reported no adverse effects of our trapping activity and were keen to continue in the study, were additional funding to be acquired.


In addition, data on local LASV outbreaks are sparse. Therefore, the local communities have vital knowledge of lived experience of potential LASV outbreaks that may not be captured by the scientific literature or public health agencies. Given the sparsity of data in the Eastern Province of Sierra Leone, drawing on the knowledge of local leaders helped to guide the design of the study protocol.


## Study design


This was a longitudinal rodent trapping study with repeated measurements nested within different land use types, nested within villages. 


### Study duration


The study was designed to be conducted over 3 years (the duration of the PhD funding). This study duration was expected to yield a sufficient sample size for the planned analyses (not time-varying), based on previous research in the same country. Delays to the start of the project due to COVID-19 travel restrictions resulted in a shortened timeline of two-and-a-half years. 


### Sampling frequency


With regards to the sampling frequency over the 3-year study period, we opted for quarterly sampling (i.e., four times annually). This was guided by several factors. First, this study was designed in the context of investigating LASV transmission, where high intensity sampling is required to ensure detection of transmission were it to occur. LASV virus is expected to be cleared 40 days post-infection. Therefore, substantially longer periods between sampling activities could result in transmission episodes being missed [safronetz_temporal_2022]. In addition, the lifespan of rodents in these settings is less than one year. Therefore, longer time periods between visits could result in a different population of rodents being sampled than those that were alive at the time during pathogen transmission [@leirs_productivity_1993; @safronetz_temporal_2022]. 


Second, data from Guinea and Nigeria suggest a strong seasonal component to LASV incidence among rodents and humans [@fichet-calvet_fluctuation_2007; @olayemi_new_2016]. Importantly different pathogen prevalence between the rainy and dry seasons was thus expected and meant that estimates of prevalence were needed from multiple time points during the year. 


Finally, as trapped rodents were euthanised and removed from the population, we did not want to affect the population structure of the small-mammal communities studied. Quarterly sampling was therefore used to balance the conflicting demands of detecting transmission and not substantially altering the studied population. This was considered an appropriate balance based on a study investigating the impact of removal trapping on rodent abundance and population dynamics in Guinea, which suggested rebound of rodent populations over short time periods [@marien_evaluation_2019].


### Sampling strategy


Next, we considered the sampling strategy required for obtaining unbiased estimates of rodent occurrence and abundance. Particularly important is the selection of the sites to sample rodents from (e.g., traps nested within trap grids set in different land use types, nested within villages) and the sampling effort (i.e., number of traps and trap nights) at each site [@stolar_accounting_2015; @stryjek_unbiased_2019]. The following section outlines the rationale for the village, grid and trap site selection and the respective sampling effort.


### Village selection


Lassa fever is endemic in the Eastern Province of Sierra Leone, with the area surrounding Kenema considered to have the greatest incidence of human infection [@kelly_housing_2013]. However, data on the village locations of incident infections are largely undocumented [@shaffer_space-time_2021]. To better understand the local epidemiology of Lassa fever, I met with the provincial Paramount Chief and regional elders, in addition to the chief medical officer at a local hospital (Panguma District Hospital), which covers a large rural catchment area. These meetings aimed to identify villages that had previously experienced Lassa fever outbreaks (not necessarily documented by public health authorities) in addition to locations where no outbreaks had been experienced. The selection of villages with experienced and no experienced outbreaks was considered important to ensure that we were not conditioning the sampling based on expected Lassa fever incidence. This led to the inclusion of two villages where Lassa fever had not previously been experienced (Seilama and Baiama) and two villages where it had been experienced (Lalehun and Lambayama).


### Trapping grids within different land use types


To estimate the occurrence of rodent species along a land use gradient in our study region, we aimed to conduct rodent trapping representative of the main land use types in Eastern Province, Sierra Leone. Land use types were grouped into villages/urban, agriculture, and forest. We therefore discounted water, marsh, and shrub land in our study. Land use type rasters of the region were produced from remote sensing data and were ground-truthed to field observations [@jung_global_2020]. Remote sensing data has several limitations in this region of West Africa. First, the transient nature of agriculture practices in the region (i.e., slash-and-burn) makes it challenging to train classification models to identify land used for agriculture, when compared to classification in regions with industrialised agricultural practices [@thenkabail_characterization_1999; @kusimi_assessing_2008]. Second, mixed use of land within the region (e.g., crops interspersed within plantations or plantations in forest settings) can lead to the misclassification of land use based solely on remote sensing [@alabi_banana_2022]. Finally, cloud cover in the region limits the number of satellite images that can be aggregated for a defined location, thus impacting the sensitivity of classification. Therefore, a combination of remote sensing and ground-truthed observations were used to select trap grids representative of forest, agriculture, and village land use. To approximate representativeness of trapping effort weighted to the area of these different land uses and human activity within them, we opted for the following setup at each of the four selected villages: a single grid in forest, four grids in agriculture (two in settings proximal to the village and two in more distal locations) and two within the villages (one in outdoor and one in indoor settings).


The selection of exact trap grid locations within the villages was guided by several factors. First, it was important that the trapping grids could be accessed in all weather conditions. Sierra Leone has a dry and a rainy season, with substantial amounts of precipitation in the rainy season degrading roads and tracks. This makes access to remote sites challenging during the rainy season. Second, areas of forest around villages may be locations of special community importance, such as gravesites or locations of ceremonies for secret societies [@lebbie_ethnobotanical_1995; @martin_role_2011; @menard_poro_2017]. The selection of trap grids was therefore conducted in close collaboration with the local communities, to ensure that sites would be accessible throughout the study period. Finally, due to the transient nature of farming practices in the region, it was important to ensure that trap grids would not be converted to different land use types during our study (e.g., conversion of forest to agriculture or agriculture left to fallow). We therefore discussed the locations of planned trap grids with the local communities to ensure these locations were not identified for significant land use conversion.


### Structure of trap grids and trap locations


Once the trap grid sites had been selected, the structure of the grids placed within these locations must be chosen. Trap lines, trap grids, trap webs, and sporadic placement of traps have all been previously used in published rodent trapping studies. In the present study, it was important that the local habitats for each individual trap did not substantially vary within a single land use type. This meant that trap lines (which often span multiple land use types due to their length) were not considered appropriate. In addition, as we aimed to infer contacts between individually trapped rodents based on the proximity of the locations at which they were detected, it was key that trapping effort was evenly distributed across the entire area of the trap grid. This meant that trap webs were not considered appropriate. We therefore opted for a cartesian trap grid structure.


To allow comparison between sampling at grid sites during repeated visits, the GPS coordinates of the outer boundaries of the trapping grid were recorded with a Garmin GPSMAP 66i. 


### Trapping effort


The number of individual traps placed within a grid constitutes one aspect of the trapping effort. In the present study, the number of traps per grid was governed by practical rather than scientific considerations, including the number of available traps in the study team’s possession and the time requirement to setup, record and bait the traps for the local study team. A total of 49 traps per grid (7 by 7 traps) was selected. Individual traps within each grid were placed approximately 7m apart, with a view to sampling an area of 2,401m^2^ within each grid. It was not feasible to ensure that individual traps were placed at the exact locations of traps at previous visits.


Finally, the number of trap nights to be conducted at each village was selected following a review of the rodent trapping studies identified in Chapter /@ref(chapter2). Studies typically reported 1-4 trap nights conducted at each location, following discussions with the local study team four nights were selected as optimal.


### Trap type selection


Commercial rodent traps were selected for use over locally produced traps. An important consideration was to ensure the ethical handling of captured rodents. Typically, locally produced traps would take the form of “snap-traps”. These aim to incapacitate a trapped rodent with a spring powered mechanism that breaks the neck of the rodent triggering the trap. However, these traps can injure the individual rather than killing them, which could result in prolonged suffering for the trapped rodent [@hice_relative_2013]. Further, as opposed to commercially produced traps, the sensitivity of the trap triggering mechanism within locally produced traps cannot be standardised, which could result in differences in the sensitivity of each trap, leading to different capture rates across individual traps [@nicolas_relative_2006]. Commercially produced traps allow the sensitivity of closure mechanisms to be altered in the field if it is noticed that the traps are not functioning as required. Finally, commercial live-capture traps do not aim to kill the trapped rodent, which allowed us to adopt humane methods of rodent killing (i.e., cervical dislocation after anaesthesia), although arguments have been made that confining individual rodents within a trap only to later euthanise them is less ethical than a quick death through a well functioning snap-trap [@nattrass_animal_2019].


Next, the selection of a specific design of commercial rodent trap impacts the detection of species. For example, the size of the trap may prevent larger rodents, such as squirrels, entering the trap and being caught [@harkins_its_2019]. We therefore selected the dimensions of the traps based on our target population of rodents and shrews (7.62cm x 8.89cm x 22.86cm). Commercial traps may be designed for single capture or multiple capture. We were interested in assaying trapped rodents for evidence of acute infection; it was therefore important that we did not allow individuals to come into contact under conditions in which viral transmission could occur. To prevent this, we selected single capture traps. Several commercially available traps met these requirements; however, Sherman traps were selected after reviewing the studies identified in Chapter \@ref(chapter2), as these were the most commonly used commercial traps in West Africa. In addition, the study team already had access to a substantial number of Sherman traps and replacement parts, thus reducing the resource needed for the traps. Local expertise in using Sherman traps already existed, which eased the implementation of the study protocol. An additional advantage of the Sherman traps was the ease at which they could be decommissioned during the day and activated at night to prevent unintended captures.


### Bait type selection


The composition of bait used within traps will impact the species of small mammals trapped. No studies in dietary preference have been conducted within the rodent and shrew communities of Sierra Leone. However, data from other locations in sub-Saharan Africa are available for *M. natalensis*, *R. rattus* and *M. minutoides*, in both wild and captive populations. The studies report a preferential consumption of raw crops, insects, and processed foods, with processed food contributing a substantial proportion of the diet when individuals are detected within human households [@iwuala_observations_1980; @mbise_bait_1995; @odhiambo_dietary_2008; @mulungu_food_2014; @mlyashimbi_relationships_2018].


Previous studies conducted in the region did typically not describe the composition of bait placed in traps. Where reported, bait that has been shown to be effective in the region include combinations of peanut paste, palm oil and dried fish [@fichet-calvet_spatial_2005; @marien_no_2017; @bonwitt_at_2017]. During the piloting of the study protocol, I compared the trap success using a bait comprised of peanut paste, palm oil and dried fish with one of peanut paste, palm oil and goat meat. No difference in trap success was observed between these two baits and so dried fish was used throughout the remainder of the study. Bait ingredients were purchased locally at each study site and combined following a standard recipe (10 parts peanut paste, 1 part palm oil, 1 part dried fish). Traps were re-baited each day to ensure the amount of bait within the trap was equivalent between trap nights.


This bait also attracted insects and off-target animals (e.g., frogs) to the traps. Off-target species were released at the site of the trap during the re-baiting process. Insects attracted to the traps likely had an impact on the detection of insectivorous shrew species within our study region (i.e., *Crocidura sp.*). Shrew species were not considered off-target small mammals as the spatial interaction between these species and rodents within our study setting was expected to alter rodent species occurrence. Previous studies have shown that shrews are potentially infected with LASV, although their ability to maintain transmission is not known [@fichet-calvet_fluctuation_2007; @kerneis_prevalence_2009; @kenmoe_systematic_2020]. Therefore, sampling shrew populations in conjunction with our rodent primary targets would improve understanding of the structure of the small-mammal community potentially involved in LASV transmission.


A further consideration in the selection of bait is the availability of alternative food sources within the environment of the trap. For example, in areas of human habitation or agricultural settings, the high availability of alternate food sources may lead to a reduced need for rodents to enter traps, overcoming their fear of novel environments (i.e., neophobia)  [@stryjek_unbiased_2019]. We did not measure the availability of alternate food sources and so were unable to disentangle the potential impact of this on the probability of detection of a rodent within a trap.


### Implementation of sampling strategy


To ensure the study protocol was implemented as intended, a trap-check form was set up to facilitate rapid entry of the status of each trap the morning after each trap night. The form was used to record whether traps were missing bait (i.e., the sensitivity of trap closure was too low), were closed but empty (i.e., the sensitivity of trap closure was too high) or contained a small-mammal or other animal.


## Data collection, storage, and processing


Data collected in the field were recorded in real-time. Initially, paper data entry forms were used. These forms were trialled during the pilot and improved following feedback from the field team. The forms required digitisation, which could lead to data entry errors and delays in reviewing for accuracy and completeness. To counter this and allow for remote support in data entry, a digital data capture tool was subsequently adopted. The OpenDataKit (ODK) is an open-source software that has been constructed to support offline data entry through powerful forms and allow multi-media data entry, including photos [@open_data_kit_odk_2023]. The ability to store data locally when offline for it to be subsequently uploaded to dedicated servers when a network connection is found is particularly valuable when conducting research in remote regions.


The data entry forms could be completed on any smart device. Initially, the field team was provided with tablets. However, they preferred to use their own smartphones for data entry as these were more portable and faster to use. The forms were accessed through a mobile ODK application (ODK Collect) with users given access to the forms required for their role [@odk_collect_odk_2023]. Data were encrypted locally after form completion and sent securely to an ODK Central server hosted by the London School of Hygiene and Tropical Medicine. Data were then downloaded from this server using the `ruODK` R client for the ODK Central API [@mayer_ruodk_2023]. The instant availability of data allowed real-time support to the field team to be provided.


Data on the following measures were obtained from all trapped rodents and shrews: age group, sex, morphological measures, biological measures, and the precise location of where the individual was trapped. Additional detail about the morphological and biological measures and the precise location of where the individual was trapped is provided below.


### Morphological measures


Data were obtained for all individuals on standard morphological measurements including weight and length of body, head, ear, hind foot and tail, in addition to the sex and reproductive status of individuals. These measurements, alongside more general characteristics, including pelage colour supported classification using the produced taxonomic key (\@ref(taxonomic-key)). Morphological measurements and reproductive status were also used to age stratify individuals into juvenile or adult age classes. Eye lenses were obtained from rodents with the aim to further classify by age using standardised eye-lens weight growth charts for species where this was available [@hardy_estimation_1983; @fichet-calvet_reproductive_2008].


Several rodent and all shrew species were not able to be differentiated based on the taxonomic key; for these species, additional molecular identification was required. Sequencing of Cytochrome b has previously been used for rodent and shrew species in West Africa and has been shown to be able to discriminate between these cryptic species [@bradley_test_2001; @lecompte_cytochrome_2002]. While some rodent species could be unambiguously classified using the taxonomic key, molecular sequencing was performed on all individuals to improve confidence in field-based identification and reduce the impact of misclassification on subsequent analysis.


### Biological measures


Biological samples (i.e., blood, tissue) were collected following established protocols for rodents and shrews [@mills_methods_1995; @fichet-calvet_chapter_2014]. Blood sampling was performed through cardiac puncture, as captured individuals had been euthanised. Cardiac puncture is expected to result in greater volumes of blood sampled compared to non-lethal techniques, such as capillary eye blood and tail vein sampling [@mills_methods_1995]. However, for very small individuals, cardiac puncture can result in insufficient volumes of blood. Therefore, for very small individuals (those that weighed <=10g), we collected blood on filter paper and obtained heart tissue samples. Filter paper samples have lower sensitivity for antibody and viral detection, which may be related to methods of elution from the filter paper [@amini_reliability_2021; @soubrier_detection_2022]. This could result in systematic biases in detection of antibodies and virus in samples from low body weight.


Samples were stored in appropriate storage media (i.e., formalin or ethanol) and placed in cool boxes on ice packs to maintain a cold chain. Ideally, samples would be stored in liquid nitrogen at the point of processing; however, this was not feasible, as liquid nitrogen is not readily available in Sierra Leone. To reduce the time that samples were stored outside of an effective cold chain, we partnered with Panguma District Hospital and Kenema General Hospital to store samples in -20°C freezers at the end of each sampling day. Long term storage of samples was within our local collaborator’s lab, located in Mercy Hospital, Bo. At Mercy Hospital, back-up power banks were able to maintain a cold chain during the daily episodes of disrupted electricity supply. However, at several points during our study, municipal power was not available for prolonged periods. It is likely that this led to samples temporarily increasing above -20°C, although it is not expected that this would have a significant impact on the degradation of antibodies during the short period they were stored prior to analysis [@amini_reliability_2021]. However, sample degradation may limit the possibility of these samples being re-used in future work. 


All sample processing and analysis (i.e., LASV serology and Cytochrome b PCR) was conducted in-country within Sierra Leone. The final stage of the analysis pipeline could not be conducted in Sierra Leone, as there were no available Sanger sequencing machines. Therefore, following sample processing, the PCR products were shipped to Germany for sequencing. Conducting all laboratory analysis in Sierra Leone was a deliberate choice to improve local ownership of the research project and to consolidate the knowledge and skills of the local workforce in the processing of biological samples. In addition, where possible, students from local higher education institutes were included in the steps of sample analysis to improve training. All samples remain in Sierra Leone for future use by the local research community and international collaborators.


### Trap locations


A trap setup form collected information on the environmental conditions of specific traps and their GPS coordinates. Photographs were used to document the habitat type where it did not meet the pre-specified options in the data collection tool. 


The detection of rodents at trap locations in the presence of imperfect detection were used to model occupancy of small-mammal species across a land use gradient, as described in Chapter \@ref(chapter3). The probability of detection of a species were it to be present within a land use type was not expected to be constant across repeated study visits [@springer_tick-_2016]. For example, changes in rodent activity would alter the probability of detection. To account for this we collated data on factors that could contribute to differences in the rate of detection (i.e., light level, precipitation and trapping effort). Rodents and shrews have been found to have variable activity in different conditions of ambient light in response to predation pressure [@paise_daily_2006; @williams_light_2014]. We were unable to accurately measure ambient light levels at individual trap locations during the sampling period and therefore used a proxy measure of moon fraction (i.e., proportion of full moon) to approximate ambient light levels. This approach may not adequately measure light level at the exact time and locations of rodent activity. Particularly, within forests light levels may be lower than in agriculture due to cover by foliage. Increased cloud cover during the rainy season may also have impacted ambient light levels compared to the dry season where higher ambient light levels may occur at ground level.


Data cleaning was performed to correct inaccuracies in data entry, including missing data. Most data inaccuracies were related to the entry of GPS coordinates, which could be remedied by asking the field team to take photographs of the GPS recorder. Other common errors included misallocating study grid numbers or visit numbers, which could be corrected using other sources of information (i.e., coordinates of traps or date of form entry). 


To support subsequent spatial analysis of the trapping data, individual traps were aggregated within grid cells. We constructed a regular grid across the trapping grids, with each cell measuring 49m2. Individual traps were allocated to a single cell with the centroid of these cells providing a standardised location of traps placed within the cells. Where multiple traps were placed within a single cell, the traps were aggregated (Appendix \@ref(trap-harmonisation)).


To facilitate the data cleaning, scripts were written in R. This allowed the original data to remain unmodified while also producing a reproducible and automated data cleaning pipeline. All code to perform data cleaning are available in a GitHub repository that reproduces the data used for analysis from the raw data uploaded to ODK Central [@simons_rodent_2022]. Finally, the availability of this R code and data entry forms can be used by other researchers to aid data collection in small-mammal sampling studies.


## Conclusion


This chapter summarises the decisions taken to design the longitudinal rodent trapping study that generated the data for the remaining chapters. I have described the steps in selecting the traps, bait and locations in which the study was conducted alongside considerations in making these decisions. I go on to describe approaches taken throughout to improve confidence in generated data and to produce a transparent pipeline from data acquisition through to data analysis. 