---
output: html_document
---

# Introduction {#introduction}

## Theoretical framework

### Rodent trapping study design

### Data exploration and visualisation

### Statistical modelling

## Aims and objectives of the thesis 

### Aim 

### Objectives

## Chapter overview

* **Chapter \@ref(background):** Background information is given. This information helps motivate future chapters and may be useful for non-subject area experts. 

* **Chapter \@ref(chapter2):** This chapter presents a study conducted to synthesise rodent trapping data from West Africa. Focussing on a comparison to consolidated data sources on rodent host species ranges, presence-absence data and host-pathogen associations. The spatial biases of rodent trapping data are explored and data is presented in a suitable format for other researchers to incorporate in their analyses to mitigate bias from other data sources.

* **Chapter \@ref(chapter3):** This chapter presents data from a two year rodent trapping study implemented as part of this thesis. This chapter focusses on rodent detection in different land use types. A model of occurrence by land use type is produced accounting for imperfect detection in observations of rodents.

* **Chapter \@ref(chapter4):** This chapter presents data on rodent antibody prevalence to *Lassa mammarenavirus* from samples obtained as part of the two year rodent trapping study. The prevalence of antibodies to this virus are described at species and land use level. Contact networks between individuals of different species are reconstructed to investigate potential transmission networks.

* **Chapter \@ref(chapter5):** This chapter consolidates data from the two previous chapters to produce a hazard map of *Lassa mammarenavirus* spillover in Eastern Sierra Leone.

* **Chapter \@ref(discussionchapter):** Results from all previous Chapters are summarised and discussed as a whole. The strengths and weaknesses of the analysis in this thesis are outlined. Further work is outlined.

## Thesis output

This thesis has produced: peer reviewed papers; preprints; talks at academic conferences and a dashboard for exploring relevant data. These outputs are detailed in the following section.

### Peer reviewed papers

* Simons D., Attfield L., Jones K., Watson-Jones D., Kock R. *Rodent trapping studies as an overlooked information source for understanding endemic and novel zoonotic spillover*, PLOSNTD, 2023, ...

* Simons D. *Lassa fever cases suffer from severe under-reporting based on reported fatalities*, International Health, 2023, ...

### Papers under review

* ...

### Software

#### Interactive tools

* **Explore Rodent Trapping Studies in West Africa**: Developed to showcase the data extracted and synthesised in the Rodent trapping studies as an overlooked information source for understanding endemic and novel zoonotic spillover article. Link: https://diddrog11.shinyapps.io/scoping_review_app/

### Talks

* **Planetary Health Alliance**

* **EEID 2022**

* **Transmissable Vaccines 2023**

## Summary

- This chapter provides an introduction to rodent borne zoonotic infectious diseases and Lassa Fever. It then motivates the remainder of this thesis. 
- An outline of the theoretical framework used throughout this thesis is given.
- The aims and objectives of this thesis are detailed.
- An overview of the chapters is provided.
- Finally the dissemination of this work so far is summarised, broken down into peer reviewed output, preprints, software output, and talks given at academic conferences.
