---
lof: true
lot: true
space_between_paragraphs: true
always_allow_html: true
link-citations: true
csl: harvard.csl
bibliography: ["references/references.bib"]
---

```{r knitr-options, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi = 320, 
                      fig.width = 8, fig.height = 8,
                      out.width = "80%", fig.align = 'center',
                      warning = FALSE, message = FALSE)
```

```{r include_packages, include = FALSE}
if (!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if (!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(thesisdown)
if (!require(pacman))
  install.packages("pacman", repos = "http://cran.rstudio.com")
pkgs =
  c("ggspatial",
    "ggsflabel",
    "googledrive",
    "here",
    "mapdata",
    "maps",
    "maptools",
    "sf",
    "tidyterra",
    "tidyverse")

pacman::p_load(pkgs, character.only = T)
```

\newpage

## Abstract {-}

```{r abstract, child = "00-abstract.Rmd"}
```

\newpage

## Thesis outputs {-}

```{r output, child = "00-thesis-output.Rmd"}
```

\newpage

## List of Acronyms {-}

```{r acronyms, child = "00-acronyms.Rmd"}
```

\newpage